const complimenti = [
    "Sei straordinario!",
    "Hai un sorriso contagioso!",
    "La tua gentilezza è ammirevole!",
    "Il tuo impegno è esemplare!",
    "Sei una fonte di ispirazione!",
    "Hai un cuore generoso!",
    "La tua positività è contagiante!",
    "Sei incredibilmente talentuoso!",
    "La tua intelligenza è impressionante!",
    "La tua creatività è senza limiti!",
    "Sei una persona fantastica!",
    "La tua resilienza è ammirevole!",
    "Il tuo entusiasmo è contagioso!",
    "Hai un grande spirito di squadra!",
    "Sei sempre pronto ad aiutare gli altri!",
    "La tua dedizione è straordinaria!",
    "La tua onestà è un valore prezioso!",
    "Sei un grande ascoltatore!",
    "Hai un senso dell'umorismo straordinario!",
    "La tua gentilezza non conosce limiti!",
    "Sei un vero leader!",
    "Il tuo ottimismo è incoraggiante!",
    "Hai un modo unico di risolvere i problemi!",
    "La tua empatia è toccante!",
    "Sei una persona di grande saggezza!",
    "La tua modestia è ammirevole!",
    "Il tuo spirito di iniziativa è unico!",
    "La tua determinazione è inarrestabile!",
    "Hai una mente brillante!",
    "Sei una risorsa inestimabile per il tuo team!",
    "La tua generosità è senza pari!",
    "Il tuo senso di responsabilità è esemplare!",
    "Sei una persona di grande integrità!",
    "La tua gentilezza verso gli altri è sorprendente!",
    "Hai un grande senso dell'umorismo!",
    "La tua sincerità è apprezzata da tutti!",
    "Sei una persona di grande fiducia!",
    "Il tuo ottimismo è un faro per gli altri!",
    "La tua energia è contagiosa!",
    "Hai una capacità unica di risolvere problemi!",
    "La tua lealtà è impareggiabile!",
    "Sei una risorsa straordinaria per la tua comunità!",
    "La tua passione è ispiratrice!",
    "Il tuo impegno sociale è lodevole!",
    "Hai un talento straordinario per l'arte!",
    "La tua perseveranza è fuori dal comune!",
    "Sei una fonte di gioia per chi ti sta intorno!",
    "La tua umiltà è ammirevole!",
    "Il tuo senso pratico è straordinario!",
    "La tua gentilezza è un faro nelle situazioni difficili!",
    "Sei una persona di grande saggezza!",
    "La tua pazienza è davvero notevole!",
    "Il tuo atteggiamento positivo è contagioso!",
    "Hai una capacità unica di motivare gli altri!",
    "La tua gentilezza è un dono per tutti!",
    "Sei una persona di grande generosità!",
    "La tua capacità di ascolto è straordinaria!",
    "Il tuo coraggio è ammirevole!",
    "La tua umanità è un esempio per tutti!",
    "Sei una persona davvero unica!",
    "La tua etica del lavoro è lodevole!",
    "Il tuo spirito di sacrificio è straordinario!",
    "Hai una capacità innata di ispirare gli altri!",
    "La tua dedizione è senza limiti!",
    "Sei una persona di grande umanità!",
    "La tua positività è una benedizione!",
    "Il tuo spirito avventuroso è ispiratore!",
    "La tua gratitudine è un esempio per tutti!",
    "Sei un vero maestro nell'arte della gentilezza!",
    "La tua modestia è una virtù!",
    "Il tuo contributo è inestimabile!",
    "La tua determinazione è un faro nella tempesta!",
    "Sei una risorsa preziosa per chi ti conosce!",
    "La tua gentilezza fa la differenza!",
    "Il tuo spirito di collaborazione è ineguagliabile!",
    "La tua saggezza è una guida preziosa!",
    "Sei una persona di grande coraggio!",
    "La tua passione per la vita è contagiosa!",
    "Il tuo entusiasmo è unico!",
    "La tua dedizione alla tua arte è ispiratrice!",
    "Hai una straordinaria capacità di motivare!",
    "La tua gentilezza è un faro di luce!",
    "Sei una fonte di ispirazione per tutti!",
    "La tua compassione è una benedizione per il mondo!",
    "Il tuo spirito di squadra è un esempio!",
    "La tua gentilezza verso gli animali è toccante!",
    "Hai un modo unico di illuminare il giorno di chi ti sta intorno!",
    "La tua cura per gli altri è lodevole!",
    "Il tuo senso di responsabilità è un faro di stabilità!",
    "Sei una persona di grande creatività!",
    "La tua perseveranza è un faro nella tempesta!",
    "La tua gentilezza senza riserve è un dono!",
    "Sei una risorsa straordinaria per la tua comunità!",
    "La tua capacità di trovare soluzioni è straordinaria!",
    "Il tuo impegno sociale è ammirevole!",
    "La tua passione per l'apprendimento è un esempio!",
    "Hai una capacità innata di diffondere gioia!",
    "La tua dedizione al benessere degli altri è sorprendente!",
    "Il tuo coraggio di affrontare sfide è ispiratore!",
    "La tua gentilezza silenziosa fa una grande differenza!",
    "Sei una persona di grande integrità!",
    "La tua risata è contagiosa!",
    "La tua gentilezza verso il pianeta è ammirevole!",
    "Sei una fonte di gioia per chi ti sta intorno!",
];

function generaComplimento() {
    const indiceCasuale = Math.floor(Math.random() * complimenti.length);
    const complimento = complimenti[indiceCasuale];
    document.getElementById('compliment').innerText = `Complimento: ${complimento}`;
}
